

name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: intall libs
        run: |
             sudo apt install libsdl2-dev libsdl2-ttf-dev lua5.3
             sudo apt install liblua5.3-dev gcc cmake
      - name: run build script
        run: |
             cmake -S . -B _build
             cmake --build _build
